# Project information
site_name: DVC_NLP_Project

# defeine TOC or order of website-
nav:
  - Home: index.md
  - Data-prep-stage: data_prep.md
  - Featurization: featurization.md

site_author: Sushant Sur
site_description: >- 
  DESCRIPTION
# Repository
repo_name: sushantsur23/DVC_NLP_Project
repo_url: https://github.com/sushantsur23/DVC_NLP_Project

# Configuration
theme:
  name: ivory
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sushantsur23
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SSur20313368
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sushant-sur-b1b98319/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sush.sur23/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
    - search:
        indexing: 'full'

copyright: |
  &copy; 2022 <a href="https://github.com/sushantsur23"  target="_blank" rel="noopener">Sushant Sur</a>

extra_css:
    - css/extra.css